multi-process proof-of-concept
yay unsoundness:
thread '<unnamed>' panicked at core\src\panicking.rs:221:5:
unsafe precondition(s) violated: slice::get_unchecked requires that the index is within the slice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `--test basic`

Caused by:
  process didn't exit successfully: `D:\Projects\blondie\target\debug\deps\basic-10e35b968cd5dbed.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)